### ISSUE TITLE
Crash on loading new master decks if OBS is fetching GDI text file

### ISSUE THREAD

**Issue by frank-h-w** [Unreal-Dan/RekordBoxSongExporter#1]
Hi,

First, let me tell how you how amazing what you are doing is! I've found you via erikrichardlarson. I have to say after trying it, it's nothing short of AMAZING

Here is the symptom I've attempted it twice to be certain that it really is a bug.
1- if the GDI source is NOT in chatlog mode, Rekordbox will crash. Since you already stated in the description that it needed to be "chatlog" mode, this is just for you to be aware that users might experience crashes if they don't do it.
2- Mini "glitch", Current track/last track don't have artist. the other files with "tracks" do.  

Here are a few comments/ideas; if you make it wow... I can try to help, I don't code in that language but I can try.
1- Is it possible to go ourselves and get other meta data? BPM (of current deck), Key? 
2- is it possible to create another output file a bit like "played_tracks" but that has more data? The one that would be most amazing would be "time" started either the play variable or when it switches to "master", Either or are great.

Once again, thanks for the amazing work. I'll be sharing this on my twitch stream, it's nothing short of amazing.

**Comment by Unreal-Dan** [comment]
Check the latest release, all files have artist - track now with the option in the launcher.

> 1- Is it possible to go ourselves and get other meta data? BPM (of current deck), Key?

Absolutely, I'll look into finding that information.

> 2- is it possible to create another output file a bit like "played_tracks" but that has more data? The one that would be most amazing would be "time" started either the play variable or when it switches to "master", Either or are great.

Do you mean the time in the track that it started? Like 1 minute into the track?

**Comment by frank-h-w** [comment]
> Check the latest release, all files have artist - track now with the option in the launcher.
> 
> > 1- Is it possible to go ourselves and get other meta data? BPM (of current deck), Key?
> 
> Absolutely, I'll look into finding that information.
> 
> > 2- is it possible to create another output file a bit like "played_tracks" but that has more data? The one that would be most amazing would be "time" started either the play variable or when it switches to "master", Either or are great.
> 
> Do you mean the time in the track that it started? Like 1 minute into the track?

1.1 - Thanks for the new artists selection. You can check this other github I used to use (you win now, i'm going to share this to everyone! amazing work mate) https://github.com/LePopal/PRACT-OBS
He enables the user to decide what metadata to output to the .txt. For instance I was using this as an example
"NOW PLAYING: %TITLE% by %ARTIST%"

This is just a nice to have, what you already provide is amazing.


2- Sorry i wasn't clear at all, my bad. I mean the way you fetch data, do you store the time deck X had a new song with a "play" (i'm assuming you have the time value of what the play was hit) and then you write in the .txt the new entry when the master deck switches; do you store that time as well? Because if you did, the "tracks_played" could have an alternative version called "tracks_played_timestamp". Which would effectively mean any DJ using your app automatically gets the complete tracklist with timestamp of any set done. = amazing stuff!!!!!!!!!!

**Comment by Unreal-Dan** [comment]
Yeah I can definitely make some configuration options in the launcher which allows for formatting the output in the files, that sounds much nicer.

> 2- Sorry i wasn't clear at all, my bad. I mean the way you fetch data, do you store the time deck X had a new song with a "play" (i'm assuming you have the time value of what the play was hit) and then you write in the .txt the new entry when the master deck switches; do you store that time as well? Because if you did, the "tracks_played" could have an alternative version called "tracks_played_timestamp". Which would effectively mean any DJ using your app automatically gets the complete tracklist with timestamp of any set done. = amazing stuff!!!!!!!!!!

I understand now, I'll look into this thanks :)

Edit: I think you should be happy with the latest release, closing this now :)

**Comment by frank-h-w** [comment]
Ill check it out tonight in my stream :) 👍

**Comment by frank-h-w** [comment]
Just wow.... I tried it, jesus christ how did you code all that fast!??
Wow!!!
