### ISSUE TITLE
Version 3.41 - BPM always at 0

### ISSUE THREAD

**Issue by frank-h-w** [Unreal-Dan/RekordBoxSongExporter#10]
Hi,

Little bug, the launcher can't display BPM (it's outputing only 0s).

The setting i've used is as follow : Replace, offset 0. 

%title% by %artist% @%master_bpm%

Thanks for the investigation!
Frank

**Comment by Unreal-Dan** [comment]
Ah thanks, I assume they must have updated the structure that holds the bpm and the bpm location must have shifted in memory. 

Let me look into that.  

I'll need to developer a better testing process that can test all of the features, I've gotten lazy in my testing before releases.

**Comment by Unreal-Dan** [comment]
Okay I have solved the issues with BPM and everything will be working in 3.42

Apologies, they added new features and the BPM shifted to a different position in memory.  

I've added some future proofing to the BPM lookup too, hopefully this shouldn't happen again.

https://github.com/Unreal-Dan/RekordBoxSongExporter/releases/tag/3.42

**Comment by frank-h-w** [comment]
Amazing hey seriously thank yoy so much for doing this hope it didn't take
you too long during your holidays! Still gota tell me where we can get
something (buy me a coffee page?)

Cheers!!
Frank

**Comment by Unreal-Dan** [comment]
No worries, I do this because I have somebody close that benefits heavily from it and I quite enjoy the work, it's my own hobby and my career.

Cheers

**Comment by frank-h-w** [comment]
Thanks! Your work is nothing less of amazing. Makes my small channel
management's much easier!

Frank
