### ISSUE TITLE
Testing BPM output and command injection

### ISSUE THREAD

**Issue by Unreal-Dan** [Unreal-Dan/RekordBoxSongExporter#11]
Hello @frank01wong I wasn't sure how else to contact you, I am working on some changes for detecting bpm changes and some other features that would allow injecting commands into rekordbox to force changes like bpm increase/decrease or play/pause to allow for exposing these features programmatically to other software.

I was wondering if you would like to help test these features, would you find benefit from a bpm-change trigger to update the output files? If this sounds interesting and you have time to help then let me know, if you have discord it might make things easier.

**Comment by frank01wong** [comment]
Hey Dan,

I'd be more than happy to help! I'm not sure i'm totally understanding the
feature but it sounds like it isn't going to be the 2 options we currently
have right? Native BPM of the track or the BPM set on the master deck when
RBE "reads" the value the first time it is sent to the .txt file ; am I
understanding that correctly?

I do have discord, user id : frank_halfwong#7131

Cheers,
Frank
