### ISSUE TITLE
Crash on master selection if deck is empty

### ISSUE THREAD

**Issue by mickaelmarin** [Unreal-Dan/RekordBoxSongExporter#13]
Hi,

To start, this tool is amazing.

I detect a bug when I load a track in deck 1 for example and if I switch master to deck 2 with deck 2 empty (no track loaded at this time) rekordbox crash.

I started to dev an android app (virtual midi controller) and I need to get the bpm of track when lauched in deck. With the original bpm information of track I can for example set the right bpm on my 14bit pitch slider.

In the future could you hook to the function when track is loaded in a deck and update output file with the bpm of the track lastly loaded ?

**Comment by Unreal-Dan** [comment]
Hello nice catch, I never tested switching the master manually I always let Rekordbox handle changing it for you.  

I will fix that bug in the next release considering it's not super important. 

If you want to add me on Discord I'd be happy to discuss other possible features you may be able to create in the virtual midi controller.  I have some features for RBSE in the works that might be interesting for you :)

Daniel # 8135
