### ISSUE TITLE
Rekordbox 6.6.2 Success

### ISSUE THREAD

**Issue by emopinata** [Unreal-Dan/RekordBoxSongExporter#14]
Just wanted to say that I got this upgrade yesterday, changed the path as necessary, and used it without any problems (that I noticed) during my stream last night. Thank you!

**Comment by Unreal-Dan** [comment]
That is good to hear, I've been working on some updates but life gets in the way and they've been stalled for a while now.  So it's definitely nice to hear that my proactive preparations has prevented issues.
