### ISSUE TITLE
Crashes when pressing play-button with rekordbox 6.6.3

### ISSUE THREAD

**Issue by MartinTicTacTrance** [Unreal-Dan/RekordBoxSongExporter#15]
When you lauch rekordbox 6.6.3 over rekordboxsongexporter and cue in A und B the tracks, after hitting the software and hardware freezes. Shutdown of hardware and restart of PC is necessary then.

**Comment by Unreal-Dan** [comment]
I've had a whole bunch of changes sitting around for a long time, including several bugfixes for crashes.  I put it together into a release but I'm not sure if I fixed the bug you describe. 

Please try 3.6 and let me know if the issue persists

https://github.com/Unreal-Dan/RekordBoxSongExporter/releases/tag/3.6

**Comment by MartinTicTacTrance** [comment]
I recorded on the weekend a couple of test mixes, today a 2 hours mix without any problems (rekordbox 6.6.3 and songexporter 3.6), so I think the issues are fixed. It feels very stable, had no issues at all!

**Comment by Unreal-Dan** [comment]
Good to hear, will close issue.  Feel free to open another if you encounter any issues.
