### ISSUE TITLE
Does not work with Rekordbox 6.6.4 

### ISSUE THREAD

**Issue by emopinata** [Unreal-Dan/RekordBoxSongExporter#17]
Just tried the Rekordbox 6.6.4 update yesterday and the launcher would start Rekordbox but nothing was getting written to the output files, noting that I didn't hear the usual "beep" when the launcher starts Rekordbox. Please let me know if there's anything I can do to help troubleshoot.

**Comment by piregg** [comment]
doesn't work for me either, a fix would be amazing if possible :)

**Comment by piregg** [comment]
I tried changing the path in the box to 6.6.4 but no luck

**Comment by Unreal-Dan** [comment]
Ah sorry for the delay guys I'll look into it, they must have changed something a little bit too much for my future proofing to handle.

**Comment by frank-h-w** [comment]
Same for me. i reverted to rekordbox 6.6.3. Anyone noticed 6.6.4 performance drop (audio artifacts) when using streaming services? (tidal). When loading tracks.

**Comment by Unreal-Dan** [comment]
interesting thanks for the heads up, sorry guys been dealing with some stuff going on in life right now and updating rbse is unfortunately not very high on my list of priorities.  

I'll try my best to get an update out asap

**Comment by frank-h-w** [comment]
On a side note, because I have no idea where to park that on github. Here's an idea, since I tend to forget to save the exported tracklists after sets:
Auto-create a "export" directory that tags the date of all create .txt files so that when the next time RBSE boots up, it doesn't overwrite files and just starts over without delegate the previous run.

Just an idea!
Cheers
frank

**Comment by erikrichardlarson** [comment]
Will take a look at this and see if I can somewhat figure out where things are breaking in the latest version, ideally it's just a new function offset for the latest version that we can hardcode like before: https://github.com/Unreal-Dan/RekordBoxSongExporter/blob/70db11cab4becef6fb2a30bff0c37a274c35e5d5/Module/EventPlayTrackHook.cpp#L113

**Comment by erikrichardlarson** [comment]
Ok yeah looks like the sig_scan failed according to the log so if we can find the EventPlayTrack function offset it shoulddd work.

**Comment by Unreal-Dan** [comment]
> On a side note, because I have no idea where to park that on github. Here's an idea, since I tend to forget to save the exported tracklists after sets: Auto-create a "export" directory that tags the date of all create .txt files so that when the next time RBSE boots up, it doesn't overwrite files and just starts over without delegate the previous run.
> 
> Just an idea! Cheers frank

This can be achieved with a "start.bat" script that first copies your existing tracklist.txt to exports/tracklist.date.txt, then launches RBSE launcher. Then instead of running the RBSE launcher directly you always use the start.bat to launch it. 

Something I'm considering for future versions is filenames could allow for tags like %date%, then it could generate the tracklist.date.txt for you.

**Comment by GForceWeb** [comment]
> Will take a look at this and see if I can somewhat figure out where things are breaking in the latest version, ideally it's just a new function offset for the latest version that we can hardcode like before:
> 
> https://github.com/Unreal-Dan/RekordBoxSongExporter/blob/70db11cab4becef6fb2a30bff0c37a274c35e5d5/Module/EventPlayTrackHook.cpp#L113

I'm a novice at hex editors but I couldn't find the eventPlayTrack function in the 6.6.4 exe. Tried looking for a similarly named function in case its name had only changed minorly but didn't find anything there either. 

Will probably need to wait for Unreal-Dan to have the time to troubleshoot it properly. Back to 6.6.3 I go for now

**Comment by Unreal-Dan** [comment]
> I'm a novice at hex editors but I couldn't find the eventPlayTrack function in the 6.6.4 exe. Tried looking for a similarly named function in case its name had only changed minorly but didn't find anything there either.

You're absolutely correct the function is just gone, so we will have to hook something else equivalent to achieve callbacks when the play button is pressed.  

Luckily I have another method that I discovered much later which should achieve the same thing... Unfortunately I've been super busy with life lately, and a little bit demotivated when it comes to writing code, sorry guys.  

I'll try to get to things asap.

**Comment by frank-h-w** [comment]
No rush mate, get your personal stuff done first. If you have some energy left, sure code it, otherwise take care of yourself mate. 
Thanks again for looking into this.

Frank

**Comment by piregg** [comment]
More than happy to donate to the cause, whats your paypal?

**Comment by Unreal-Dan** [comment]
> More than happy to donate to the cause, whats your paypal?

Much appreciated but I truly don't need money, I have a cushy developer job with a fantastic salary.  

I will set aside some time this weekend to fix this.

**Comment by Unreal-Dan** [comment]
https://github.com/Unreal-Dan/RekordBoxSongExporter/releases/tag/3.7

**Comment by emopinata** [comment]
Just tested it with an hour long set I did last week, no issues so far! The real test will be my next four hour stream. Thank you so much @Unreal-Dan for continuing to support this, we very much appreciate it ❤️

**Comment by frank-h-w** [comment]
Not a problem at all! Take the time you need!
Frank
