### ISSUE TITLE
Feature Request: Deck Specific Track Data

### ISSUE THREAD

**Issue by GForceWeb** [Unreal-Dan/RekordBoxSongExporter#18]
Would love to be able to get deck-specific information out of RBSE for situations where the "master" track data isn't sufficient, such as 3/4 deck mashup mixes where a single track does not accurately depict what's actually being played. For my use case, just artist/title would be sufficient but others might benefit from access to other track metadata as well. I'd envisage this would end up looking similar to the deck BPM implementation with variables like %deck1_title% %deck1_artist%, %deck2_title% etc and the values would update whenever a new track is loaded to that deck. 

I understand your time is limited on this project and if it's not something you have the time to work on, but you think is feasible to bolt on top of what you've already built and have some general notes on where to look that might help me then I can dabble with it myself. C++ isn't something I have that much experience with but I can usually stumble my way to success when given the time and a good starting off point

**Comment by Unreal-Dan** [comment]
So there are a few issues with this, the first issue is the system is designed to log information from the master-deck when the master switches to that deck.  If you wanted to log information for say deck1, then you would probably want that to trigger specifically when deck1 changes -- right?  

So this would involve changing how the system triggers, or at least changing when it performs the logging.  You'll have to give me more information to describe when you want this information logged so I can direct you how to change that.

-----

A separate issue, unfortunately, tags aren't free. I can only have about 64 %tags% before I need to re-design the approach.  Currently there is 38 tags.  

Adding all of these single-deck tags for each deck would actually overflow past 64, so it would be a high cost for a low value change. 

However, I can definitely direct you to changing the code to include new tags.  

It's quite easy to add tags, the steps are:

1. Define a new tag bitflag on line 123 in OutputFiles.cpp of the Module: https://github.com/Unreal-Dan/RekordBoxSongExporter/blob/master/Module/OutputFiles.cpp#L123

This would look something like this (deck1 and deck2 title and artist):

```
     TAG_DECK1_TITLE = (1ULL << 38),
     TAG_DECK2_TITLE = (1ULL << 39),
     TAG_DECK1_ARTIST = (1ULL << 40),
     TAG_DECK2_ARTIST = (1ULL << 41),
```

The number at the end of the line needs to increase by 1 each time, to a max of 63.

2. Set the bitflag if your %tag% is found in the format string on line 565: https://github.com/Unreal-Dan/RekordBoxSongExporter/blob/master/Module/OutputFiles.cpp#L565 

This would look something like this:

```
  if (format.find("%deck1_title%") != string::npos) { format_tags |= TAG_DECK1_TITLE; }
  if (format.find("%deck2_title%") != string::npos) { format_tags |= TAG_DECK2_TITLE; }
  if (format.find("%deck1_artist%") != string::npos) { format_tags |= TAG_DECK1_ARTIST; }
  if (format.find("%deck2_artist%") != string::npos) { format_tags |= TAG_DECK2_ARTIST; }
```

3. Then finally replace the tag in the output line if the bitflag is present, on line 648: https://github.com/Unreal-Dan/RekordBoxSongExporter/blob/master/Module/OutputFiles.cpp#L648

This would look something like this:

```
  if (format_tags & TAG_DECK1_TITLE) { 
      track_data track;
      track.load(0);  // load track data for deck 0
      replace(out, "%deck1_title%", track->title); 
  }
  if (format_tags & TAG_DECK2_TITLE) { 
      track_data track;
      track.load(1);  // load track data for deck 1
      replace(out, "%deck1_title%", track->title); 
  }
  if (format_tags & TAG_DECK1_ARTIST) { 
      track_data track;
      track.load(0);  // load track data for deck 0
      replace(out, "%deck1_title%", track->artist); 
  }
  if (format_tags & TAG_DECK2_ARTIST) { 
      track_data track;
      track.load(1);  // load track data for deck 1
      replace(out, "%deck1_title%", track->artist); 
  }
```

I believe those changes should conclude adding 4 new tags:

```
  %deck1_title%
  %deck2_title%
  %deck1_artist%
  %deck2_artist%
```

There is still the aspect that they will only log when the master switches.

**Comment by GForceWeb** [comment]
Really appreciate the really detailed response. This gives me plenty to work off. 

In regards to the trigger for each deck logging, I'm guessing just firing whenever a track is loaded to the deck would be the easiest even though it's potentially going to trigger for tracks that are loaded but don't end up getting played (which is fine as it's not meant to be a playlist in the same way the master tags are). The most accurate trigger would probably be based off the deck being included in the master mix but I'm not sure if there's any way to trigger based on that. Side tangent: if there is a way to trigger based on that having some sort of status tag to show if a deck is live or not would be cool as well.

Thanks for the context regarding the max 64 tags. I guess for my own implementation I can do whatever up to that 64 limit but for a potential pull request into the main repo we'd want to limit how many are included. Maybe just a single %artist% - %title% tag for each deck which I'd imagine would be the most common use of this feature.

**Comment by Unreal-Dan** [comment]
If you want to trigger updates based on the file being loaded there's a simple little hack you can do

https://github.com/Unreal-Dan/RekordBoxSongExporter/blob/master/Module/LoadFileHook.cpp#L34

Around line 35 (after the call to set_track_id) you're going to want to do something like:

```
push_deck_update(deck_idx, UPDATE_TYPE_NORMAL);
```

Then you're probably going to want to disable the NotifyMasterChange hook so that you only receive updates when you load files and not when the master changes. You can disable the hook by commenting out this line:

https://github.com/Unreal-Dan/RekordBoxSongExporter/blob/master/Module/DllMain.cpp#L133

That should make the 'normal' deck update which logs track changes to occur every time you load a file, although I haven't tested this change.  You should be able to combine this with the other changes I've described to achieve what you want.  

If you want to put together a pull request I can review it, but I won't be merging any features that are too specialized.  You can easily just create a custom build for things like that.

**Comment by Unreal-Dan** [comment]
going to close this feel free to open another issue if you have any more questions
