### ISSUE TITLE
Does not work in Rekordbox >=6.6.11

### ISSUE THREAD

**Issue by DJDeadSignal** [Unreal-Dan/RekordBoxSongExporter#20]
Hi @Unreal-Dan,

Looks like Pioneer moved the goalposts again! 🙄

RBSE ([latest build](https://github.com/Unreal-Dan/RekordBoxSongExporter/releases/tag/3.7)) successfully launches rekordbox 6.6.11 but there is no change to the output files.
Downgraded to 6.6.10 and it functions properly.

Brilliant work. Thank you for this project. 💯 I can confirm that this has worked seamlessly for every RB point release until now.

Here's the link for previous releases for anyone who wants to downgrade (no need to uninstall latest): https://rekordbox.com/en/support/faq/v6/#faq-q600141

**Comment by frank01wong** [comment]
Confirmed, same issue here since 6.6.8 sadly!

**Comment by frank-h-w** [comment]
Works until 6.6.8 Also, is there somewhere in the code some point of how we could potentially detect the issue ourselves and perhaps help you with all this? I know you are quite busy! let us know!
frank

**Comment by Unreal-Dan** [comment]
I'll take a look this weekend thanks for the heads up guys

**Comment by hydra-sl** [comment]
was woking great upto 6.6.10, stopped working with 6.611, and also not working for 6.7.0.

This is a great tool, thank you . I hope it will continue, even if i have to pay a small fee.

**Comment by Unreal-Dan** [comment]
@hydra-sl I definitely supported 6.7.0 at one point... That's strange if it no longer works.

Sorry guys I'm just looking into this now, hopefully I can future proof it some more

**Comment by hydra-sl** [comment]
Hi Dan,   6.7.0 was only released about 1-2  week ago , so i think you mixed up the version number .
6.6.10 -> working with RBSE
6.6.11 -> NOT working with RBSE
6.7.0 -> NOT working with RBSE

**Comment by Unreal-Dan** [comment]
https://github.com/Unreal-Dan/RekordBoxSongExporter/releases

**Comment by DJDeadSignal** [comment]
Hey @Unreal-Dan 

Thank you for looking at this.
I'm testing on 6.7.1 tonight and I'll let you know if there's any issues.

Cheers,
Rich.

**Comment by DJDeadSignal** [comment]
No issues in 6.7.1. 5h set was seamless.

Thank you @Unreal-Dan :)
