### ISSUE TITLE
Not working in 6.6.11 nor in 6.7.0

### ISSUE THREAD

**Issue by hydra-sl** [Unreal-Dan/RekordBoxSongExporter#21]
Seems pioneer are busy these days shifting the code around.

I have gone back to 6.6.10, this song exporter is more value to me than the new features in RB 6.7 But at some point we will be forced again to upgarde , like when they removed KUVO. Active plans could not link to the servers.

**Comment by Unreal-Dan** [comment]
https://github.com/Unreal-Dan/RekordBoxSongExporter/releases
