### ISSUE TITLE
"unexpected rekordbox error"

### ISSUE THREAD

**Issue by frank-h-w** [Unreal-Dan/RekordBoxSongExporter#23]
Hi,

With both the 3.8 and 3.81 running either 6.71 or 6.7.2 after loading one track, they both make rekordbox crash with the error message....
![image](https://github.com/Unreal-Dan/RekordBoxSongExporter/assets/71349100/336d5ec6-66e5-478d-88d1-feae210b4667)

Let me know if im alone experiencing this
Frank

**Comment by Unreal-Dan** [comment]
interesting you are the first person to report it so far, it was working fine for me.  

Give your current configuration, it might just be one of the tags you're using.  

Try using a very basic configuration with 1 output file and 1 tag and see if it persists.

**Comment by getaped1** [comment]
I am getting the same error using 3.8.1 and 6.7.1. It does not happen all the time, but when it does, its always the 1st track loaded.

**Comment by Unreal-Dan** [comment]
So you mean when you first start up the program this happens sometimes when the first track is loaded?

But not during a session at all right? 

Do you always launch via the launcher? Or do you launch rekordbox first then the launcher after?

**Comment by getaped1** [comment]
Yes, it only happens when I first start RB, loading the 1st track. Never in a middle of a set.

Yes, always use the launcher only.

**Comment by Unreal-Dan** [comment]
Try starting rekordbox first, give it a few seconds once the window has opened to fully load, then hit "launch" in RBSE launcher.  

The launcher will detect Rekordbox already open and simply inject the module.  

Let me know if you can reproduce the crash with this approach, if you cannot reproduce at all this way then it gives me a good idea what the problem is.

**Comment by frank-h-w** [comment]
Oh I always thought the launcher couldn't inject unless it was used to
start rekordbox in the first place. Is there a way to be certain the inject
worked?

Cheers
Frank

**Comment by getaped1** [comment]
> Try starting rekordbox first, give it a few seconds once the window has opened to fully load, then hit "launch" in RBSE launcher.
> 
> The launcher will detect Rekordbox already open and simply inject the module.
> 
> Let me know if you can reproduce the crash with this approach, if you cannot reproduce at all this way then it gives me a good idea what the problem is.

Using the launcher after RB is started does not work. It clears out the OutputFiles and makes them all empty files like it should, but when I play anything it does not save to files.

**Comment by frank-h-w** [comment]
I use these tags @Unreal-Dan:
NOW PLAYING: %title% by %artist%  | %key% | @%rt_master_bpm% bpm
%time%,%title%,by,%artist%,%key%

**Comment by frank-h-w** [comment]
> 

Hi @Unreal-Dan , i can confirm @getaped1's observation, i get the exact same behavior. Rekordbox is detected yes, and the output files get cleared (final creation date changes to the moment you click) but then nothing gets logged in the .txt outputs.

That being said, the tracks don't crash anymore (but the module doesn't seem to work either!)
Frank

**Comment by Unreal-Dan** [comment]
sorry guys been busy, I will look at this soon.  In the meantime just use an older version of recordbox if you don't mind.

**Comment by frank-h-w** [comment]
np!take the time you need

**Comment by getaped1** [comment]
So I've noticed that it doesn't appear to happen if I load and play a track in Deck 1 first. But if I load a track in Deck 2 first and play first, it always happens. This is when using the launcher to load RB.

**Comment by Unreal-Dan** [comment]
> So I've noticed that it doesn't appear to happen if I load and play a track in Deck 1 first. But if I load a track in Deck 2 first and play first, it always happens. This is when using the launcher to load RB.

thanks this is really good information, anything else like this you can discover will undoubtedly help me. 

Apologies will look soon still wrapping up some other things

**Comment by Wietjuh** [comment]
So, i also had this happen to me when loading tracks from a streaming service like tidal in RB, after 30 ish seconds it freezes, plays the track without updating the screen and throws the above error. I'd gladly make a post with my debug info if you like.

**Comment by hydra-sl** [comment]
I have had the same issue on 6.7.1 6.7.2 6.7.3 6.7.4 6.7.5.......afetr re-installed RB , it worked ok until the windows update i got this week, now no matter what i try it brings RB to a screatching halt ,,, literally it screates lol... Hope you find some time dan to take a look... Love your plug, in

**Comment by Unreal-Dan** [comment]
https://github.com/Unreal-Dan/RekordBoxSongExporter/releases/tag/3.82

Give this a try guys I fixed a crash but I'm not sure if I fixed everything, if anybody still has issues just open a new issue
