### ISSUE TITLE
Same bug - unexpected crash

### ISSUE THREAD

**Issue by frank-h-w** [Unreal-Dan/RekordBoxSongExporter#24]
Hi Dan,

The trackid works with 6.7.5 but it still crashes on first track loaded if deck 1. I'll attach the error log (i managed to make it crash 3 times, trying loading from a different deck. It seems that if you manually set a deck to "master" before the track starts playing with the fader up, it seems to crash.

Frank

**Comment by Unreal-Dan** [comment]
ah interesting, I'll take a look. 

Just to confirm, does this prevent you from using it? Or is it just an edge condition use case?

**Comment by frank-h-w** [comment]
Rekordbox crashes if you click OK on the error message. I haven't tried to ignore the error given it's while i stream; didn't want to risk it. The DMP files can't be loaded here sorry

**Comment by Unreal-Dan** [comment]
You can email the dmp file to my gmail, unrealdanmail on gmail, that might help me out. Thanks

**Comment by Unreal-Dan** [comment]
It seems to be related to the bpm, are you using bpm tags? Can you post your tags?

This is definitely a bug that only you are facing and I cannot reproduce it, the dmp files helped and pointed me towards %bpm% but I cannot reproduce the crash in the same place and I'm not sure why.

Are you using a streaming service to load your tracks? Or are they files on the disk?

Does this happen with every single track? Or is it perhaps only specific tracks?

**Comment by frank-h-w** [comment]
Hey Dan,

i'm using Tidal streaming for the tracks (FLAC format if it helps). For the
tags, i'm using :

%rt_master_bpm%    and  %bpm% . I can revert to  %master_bpm% and try to
see if it still crashes.

It happens whenever i start the hack , automatic crash doesn't matter what
track but i sense having a "master RT" might be the issue since you can't
trigger a change of BPM on the very first track might be why.
Frank

**Comment by Unreal-Dan** [comment]
it seems the crash was related to the propagation of a %bpm% update, and it's quite possible that is a result of using a track from tidal...

Try loading a track that exists on your local filesystem and see if it still crashes, I may need to do some testing with tidal to get that working.

**Comment by Wietjuh** [comment]
I noticed if you click master before track load it doesn't crash, i've had it with al kinds of files, but ever since i click master before track load it holds up nicely. Also i've disabled the bpm tag completly.

Maybe this will help troubleshooting.

I could A/B test coming days, i'll come back to this

**Comment by frank-h-w** [comment]
> I noticed if you click master before track load it doesn't crash, i've had it with al kinds of files, but ever since i click master before track load it holds up nicely. Also i've disabled the bpm tag completly.
> 
> Maybe this will help troubleshooting.
> 
> I could A/B test coming days, i'll come back to this

Hey, you might be on to something, i gave it a shot and when you look at the output file (i made one that tracks everything from the start) and it looks like this (i;ve forced master deck on 1, before loading a tidal track in)


        (00:00:00),,by,, 
        (00:00:05),Acheron (Original Mix),by,2Pole,5A 
        (00:00:37),Decipher,by,A.D.H.S.,8B 

It indeed did not crash using that little workaround
Frank

**Comment by Unreal-Dan** [comment]
That's quite interesting, I wonder what is happening... At the very least I should be able to harden against this so it doesn't crash.

**Comment by Wietjuh** [comment]
I'm on a holiday now, but ever since disabling bpm and I click Master before load it works for me.

Even tho I'd love the bpm function, it should not let the program hard exit and force close RB.

If I can do any logging or testing for you to reproduce, let me know

**Comment by Unreal-Dan** [comment]
I suspect removing %bpm% is the main reason you don't crash, but selecting the master likely also has something to do with it.  

I agree, even if perhaps the first bpm fetch fails it should not outright crash the program and I should be able to find a way around it.

The main problem is I don't have tidal so I can't reproduce this bug, I haven't looked recently but what I recall is it only happened with tidal tracks + the %bpm% tag.  

Can you confirm whether it happens for any other kinds of tracks?  Specifically, does it happen for any tracks you have on your local PC as a file?  Or does it only happen with tracks from tidal?

**Comment by Wietjuh** [comment]
I had the same issue with local files, but had it in the past (since 6.0.1 rb) with Tidal and Beatport tracks when they didnt load up quick enough. And I also assume that it only stores the database entry (the tracks are filenames TIDAL:2646282)

I also know they don't send the bitrate and filesize decently.

If you need anything, like logs or something, let me know, I'll post when I'm back home after my holiday

**Comment by Unreal-Dan** [comment]
Okay I don't know what the problem is, I also didn't really investigate, but I don't want to keep you guys waiting forever.

I do know the issue is related to BPM so I have hardened some code around fetching the BPM with the hope that it might prevent the crash, but I need one of you to test it.

I've built a custom version of RBSE 3.8.2 which uses this additional hardening around the BPM fetch.

Could one of you please test this and see if you can get it to crash with %BPM% on the tidal tracks?
[RekordBoxSongExporter3.8.2-TEST.zip](https://github.com/Unreal-Dan/RekordBoxSongExporter/files/13644682/RekordBoxSongExporter3.8.2-TEST.zip)

**Comment by Wietjuh** [comment]
I'll have a test tomorrow, should I enable logging or collect something?

**Comment by Unreal-Dan** [comment]
Nah just try to make it crash, if it doesn't crash then success.  If it does crash then I'll have to try some other things. Ultimately I'm just trying to put a bandaid on the issue and not really trying to fix it right now

**Comment by Wietjuh** [comment]
So far so good, I think this should've done the trick. Testing out master bpm right now one more time

**Comment by DeejScorpio** [comment]
Hey Dan, first off love the app..truly amazing mate. I just wanted to let you know I am getting the same crash when using the BPM tags. Here's my experience:

- All my music is local, no streaming services. They're on a network drive so I tried to load locally on the computer and it still crashes.
- Removing the BPM tag stops the crash
- I tried the test version you posted and same issue. Crashes on start of track and force closes Rekordbox.

Weird thing is, is if I do not have my computer hooked up to my controller, the BPM tag works fine. Only when I am hooked up to it does it crash. (Running a DDJ-1000)

Cheers again!

**Comment by Unreal-Dan** [comment]
Thanks I'm glad this could be of use to people.  

Interesting, seems you have different results from Wietjuh?

Do you get a crashdump? Could you send it to unrealdanmail on gmail I'll take a look and see where the module is crashing and see if I can bandage it the same.

**Comment by DeejScorpio** [comment]
Shot it over to you, cheers again!

**Comment by Unreal-Dan** [comment]
as per email discussion with deej he was accidentally running the old version, the test version seems to be working well, I will release it

**Comment by Wietjuh** [comment]
I can confirm that I didn't have issues anymore.
