### ISSUE TITLE
Added modified code to improve RekordBoxSongExporter

### ISSUE THREAD

**Issue by MartinTicTacTrance** [Unreal-Dan/RekordBoxSongExporter#5]
Hello,
I added a couple of stuff on my own, I wonder if you're interested to add this in future releases. This works with the current latest version 2.5.
The features which are listed are:

- creating a timestamp with each start of the program, which doesn't get deleted and includes information like time (in dj mix), tracknumber, and the format you want gets written, e.g. _2021-4-23-18-49-20_played_tracks.txt, something like this: 
(00:00:00) 1. Somna & Noire Lee - Beside You (Sean Tyas Extended Magikal Mix) [Magik Muzik]
(00:00:25) 2. Zirenz - Edge Of Space [Whiteroom Mix] 
(00:00:51) 3. Matt Bukovski & Tiff Lacey - Speak Your Name (Extended Mix) [AVA White]
- a couple of methods which remove different patterns from file names. I have my tracks saved in this formats: Artist - Title (Remix) - KEY - BPM, or Artist - Title [Remix] - KEY - BPM. The methods remove the patterns ") -" or "] -" and replace them, so the KEY and BPM won't get displayed
- basic writing separate output to artist.txt, title.txt, label.txt and linebreak.txt. the last one includes artist, title and label in one file with a CR after each information
- the last feautre checks, if a label is set or not, if it is, it ats "[" and "]" around the label, if it's empty, not, so it won't be written to the output files

I'm not the most talented programmer in the world, so this might need some serious code optimizations here and there, plus I couldn't make a better code refactorization like this, so with each update to RekordBoxSongExporter it's always a hassle for me to re-add my code back :)

Curious about your feedback!

Best regards,
Martin
http://www.TicTacTrance.com

The modfied code will be added to OutputFiles.cpp:

```
        // server mode?
        if (config.use_server) {
            // in server mode send the track to the server for logging
            send_network_message(track_str.c_str());
            info("Sending track [%s] to server %s...", 
                track_str.c_str(), config.server_ip.c_str());
        } else {
            // otherwise in non-server mode just directly update the log 
            // files with this new track

            // MARTIN MODFIED BEGIN
            track = martinModify(track);
            track_str = build_output(&track);
            // MARTIN MODFIED END

            update_log_files(track_str);
            info("Logging track [%s]...", track_str.c_str());
        }
        
    } 

....

    // append the artist and track to the global log
    string log_entry;
    if (config.use_timestamps) {
        // timestamp with a space after it
        log_entry += get_timestamp_since_start() + " " + to_string(TRACKCOUNT) + ". "; // MARTIN MODIFIED
    }
    // the rest of the current track output
    log_entry += tracks.front() + "\r\n";
    if (!append_file(get_log_file(), log_entry)) {
        error("Failed to log track to global log");
    }
    TRACKCOUNT = TRACKCOUNT + 1; // MARTIN MODIFIED
}

```
My code:
```
// MARTIN MODFIED BEGIN

struct tm newtime;
__time32_t aclock;

const string currentDateTime() {

    const time_t tStart = time(0);
    //  Current time structure
    struct tm tmStart;
    localtime_s(&tmStart, &tStart);

    //  Report
    //string ausgabe = to_string((1900 + tmStart.tm_year) + tmStart.tm_mon + tmStart.tm_mday + tmStart.tm_hour + tmStart.tm_min + tmStart.tm_sec);
    string Year = to_string(1900 + tmStart.tm_year);
    string Month = to_string(1 + tmStart.tm_mon);
    string Day = to_string(tmStart.tm_mday);
    string Hour = to_string(tmStart.tm_hour);
    string Min = to_string(tmStart.tm_min);
    string Sec = to_string(tmStart.tm_sec);

    return "_" + Year + "-" + Month + "-" + Day + "-" + Hour + "-" + Min + "-" + Sec + "_";
}

const string mytime = currentDateTime();
int TRACKCOUNT = 1;

string ReplaceAll(string str, const string& from, const string& to)
{
    size_t start_pos = 0;
    while ((start_pos = str.find(from, start_pos)) != string::npos) {
        str.replace(start_pos, from.length(), to);
        str.erase(start_pos + 1, str.length());
        start_pos += to.length(); // Handles case where 'to' is a substring of 'from
    }

    return str;
}

string ReplaceAllTwo(string str, const string& from, const string& to) {
    size_t start_pos = 0;
    while ((start_pos = str.find(from, start_pos)) != string::npos) {
        str.replace(start_pos, from.length(), to);
        start_pos += to.length(); // Handles case where 'to' is a substring of 'from'
    }
    return str;
}

string get_log_file()
{
    return get_dll_path() + "\\" + mytime + TRACK_LOG_FILE;
}

string get_cur_artist_file()
{
    return get_dll_path() + "\\" + "artist.txt";
}

string get_cur_title_file()
{
    return get_dll_path() + "\\" + "title.txt";
}

string get_cur_label_file()
{
    return get_dll_path() + "\\" + "label.txt";
}

string get_cur_linebreak_file()
{
    return get_dll_path() + "\\" + "linebreak.txt";
}

track_data martinModify(track_data myTrack)
{
    string titleModified = "";
    string titleModified2 = "";
    titleModified2 = ReplaceAll(string(myTrack.title), string(") -"), string(")"));
    titleModified = ReplaceAll(string(titleModified2), string("] -"), string("]"));
    myTrack.title = titleModified;
    rewrite_file(get_dll_path() + "\\" + "title.txt", titleModified);
    rewrite_file(get_dll_path() + "\\" + "artist.txt", myTrack.artist);
    rewrite_file(get_dll_path() + "\\" + "label.txt", myTrack.label);

    if (myTrack.label.empty())
    {
        myTrack.label = "";
        rewrite_file(get_dll_path() + "\\" + "linebreak.txt", myTrack.artist + "\n" + "\n" + titleModified + "\n" + "\n" + myTrack.label + "\n" + "\n");
    }
    else
    {
        myTrack.label = "[" + myTrack.label + "]";
        rewrite_file(get_dll_path() + "\\" + "linebreak.txt", myTrack.artist + "\n" + "\n" + titleModified + "\n" + "\n" + myTrack.label + "\n" + "\n");
    }
    return myTrack;
}

// MARTIN MODFIED END

```

**Comment by Unreal-Dan** [comment]
Thanks for taking interest in this!

Do you think you could try to format your changes as a  pull request?

You will need to fork this repository onto your github, then commit the changes to your forked repository, then github should offer an option to create a pull request for your changes.

This allows me to see the differences of what you've changed much easier, it also allows me to leave comments or notes about improvements you could make before I merge the changes.

And then once all is good it allows me to automatically merge the changes through github itself.

Additionally, you will be recognized in the repository history for the work you did.

If you have any trouble I'm sure you can find some guides on google for creating pull requests.

After that I'd be happy to dig deeper into your changes and give you some more feedback.

Feel free to create a new issue if that's the only way to open a pull request, we can always just close this one and move the information over :)

Thanks again.

**Comment by Unreal-Dan** [comment]
Hello, it seems you may have forgotten about this ticket :)

I have pushed an update for version 3.0 which brings much more capability in configuring the output files, try out this new version and see if it solves your issues.
