### ISSUE TITLE
Connection drops version 3.2

### ISSUE THREAD

**Issue by frank-h-w** [Unreal-Dan/RekordBoxSongExporter#7]
Hi!

It works well but sometimes the connection is lost in server mode and there's no way to "restart" the link between the 2 machines other than closing rekordbox & the server which is possible during a live stream.

Is there a work around?

Thanks!

Frank

**Comment by Unreal-Dan** [comment]
I could look to build some fault tolerance into the netcode so that if a connection is dropped it can try to reconnect periodically, would that solve your issues?  

The server is already built to continue listening for future connections if the connection is dropped, but if the connection freezes then it will time out based on default TCP timeout which is 72 seconds I think.

The software itself shouldn't drop a connection for any reason.

**Comment by frank-h-w** [comment]
Hi Dan,

I was thinking about it, it's not the software, i think it's if the
connection on the 2nd PC drops, the server stops being able to
receive information and you need to restart the main rekordbox PC and
restart the server. That's the issue, is there a workaround?

Thanks!

Frank

**Comment by Unreal-Dan** [comment]
Sorry for the delay I totally missed this reply, unfortunately if the connection is just dropping from spotty connectivity then the connection will freeze as per TCP connection rules and timeout for 72 seconds.  

There's really not much I can do without overhauling the server into a multithreaded model that would allow it to accept more connections while one is still active.  Perhaps I will consider this in the future but it's definitely not a priority.

Your best bet might actually be to try and write a script/program yourself that can:
 1) ping google.com to check network connectivity
 2) kill the server if network dies
 3) re-launch the server

This is probably not too hard with a simple batch file and some googling

**Comment by frank-h-w** [comment]
I totally understand, way too complicated. I found a work around, i now
instead use window's internal shared network drive and i take the output
files from the local network connection rather than via server mode; my
wifi connection isn't always the best at home this is a good enough work
around. You can close the ticket!

**Comment by Unreal-Dan** [comment]
ah yes I once suggested this to somebody before the server existed but they cited how windows 10 often has issues with shared folders from windows 7/8 not appearing -- which I experienced a lot myself too.  

Glad you could resolve it and glad my software has continued to be useful
