### ISSUE TITLE
Will Rekordbox 6.6.1 be supported?

### ISSUE THREAD

**Issue by thanik** [Unreal-Dan/RekordBoxSongExporter#8]
As 6.6.1 was released on 30 November, will this version be supported soon?

Thanks!

**Comment by Unreal-Dan** [comment]
Thanks for the heads up, I will add support

**Comment by Unreal-Dan** [comment]
Hello @thanik I have released support for 6.6.1

https://github.com/Unreal-Dan/RekordBoxSongExporter/releases
